# CPU > 80%
alarm: cpu_usage_high
on: system.cpu
lookup: average -3m unaligned of user,system,softirq,irq,guest
units: %
every: 1m
warn: $this > 80
crit: $this > 95
info: CPU usage is high
to: sysadmin

# RAM > 80%
alarm: ram_usage_high
on: system.ram
lookup: average -1m unaligned of used
calc: ($this * 100) / ($used + $free + $cached + $buffers)
units: %
every: 1m
warn: $this > 80
crit: $this > 95
info: RAM usage is high
to: sysadmin

# SWAP > 80%
alarm: swap_usage_high
on: system.swap
lookup: average -1m unaligned of used
calc: ($this * 100) / ($used + $free)
units: %
every: 1m
warn: $this > 80
crit: $this > 95
info: SWAP usage is high
to: sysadmin

# DISK > 80%
alarm: disk_space_high
on: disk_space._
lookup: average -1m unaligned of used
calc: ($this * 100) / ($avail + $used + $reserved_for_root)
units: %
every: 1m
warn: $this > 80
crit: $this > 95
info: Disk usage is high
to: sysadmin