  GNU nano 7.2                                                                                                                 health.d/stream.conf *                                                                                                                         

[stream]
    enabled = yes

[a1b2c3d4-e5f6-7890-abcd-ef1234567890]
    enabled = yes
    default history = 3600
    default memory mode = ram
    health enabled by default = auto
    allow from = *
